<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NanoService\NanoService.csproj" />
    <ProjectReference Include="..\..\src\NanoTransport\NanoTransport.csproj" />
    <ProjectReference Include="..\..\examples\NanoService.Demo.Shared\NanoService.Demo.Shared.csproj" />
  </ItemGroup>
</Project>
