<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>UnityVerify.LoadGen</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NanoService" Version="4.5.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Unity\Assets\Scripts\Shared\VerifyMessages.cs" Link="Shared\VerifyMessages.cs" />
    <Compile Include="..\Unity\Assets\Scripts\Shared\VerifyConverters.cs" Link="Shared\VerifyConverters.cs" />
    <Compile Include="..\Unity\Assets\Scripts\Shared\VerifyClient.cs" Link="Shared\VerifyClient.cs" />
  </ItemGroup>
</Project>
