<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TouchSocket" Version="4.3.1" />
    <PackageReference Include="TouchSocket.Core" Version="4.3.1" />
  </ItemGroup>

</Project>
